apiVersion : apps/v1
kind: Deployment
metadata:
  name: <deployment_name>
  namespace: <namespace>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <deployment_name>
  template:
    metadata:
      labels:
        app: <deployment_name>
    spec:
      containers:
        - name: dx29-termsearch2
          image: <acr_server>/dx29-termsearch2:<image_tag>
          ports:
          - containerPort: 8080
          resources:
            requests:
              cpu: 0.90
              memory: "1.50Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: dx29-termsearch2
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: <deployment_name>
